[package]
name = "fluffhammer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"
binary-reader = "0.4.5"
colored = "2"
clap = { version = "3.2.8", features = ["derive"] }
